### ISSUE TITLE
Consider rewrite in Haskell or Idris

### ISSUE THREAD

**Issue by ejconlon** [ejconlon/idream#1]
If this gets any more complicated and people really start using it we may want to firm things up.  I would rather wait until the design and ecosystem questions are settled, though.

**Comment by luc-tielen** [comment]
Hi,
I replied to your reddit post a few days ago.. been working on a Haskell variant (which is what I'm more familiar with.)
But I see that you're still committing so it will probably be a while before I catch up :).

So far I did the JSON decoding part for package (sets) and projects + option parser logic.
Next up is rest of logic under main.py.
Code can currently be found at [my fork](https://github.com/luc-tielen/idream.git) (note that this is very much work in progress!).

So far, your code looked pretty good but the option parser probably could be more focused?
With a good set of commands the development process could be split into small, composable pieces.
Maybe best if we discuss this somewhere else (irc or whatever), if you want to?

Feedback welcome ofcourse!

**Comment by ejconlon** [comment]
Awesome! I would be happy to merge it! Are there any parts you would like me to work on?

**Comment by luc-tielen** [comment]
Well I've been busy the past few days with other stuff so I still got most of main.py ahead of me :)
I will create some issues for stuff I would change (mostly option parser / commands we need to pass). 
I'm not that familiar with package sets yet so I have to read up on that, maybe you can help me out there?
For now I will commit to another branch, and then we can merge that branch once it is up to speed with the python variant.

**Comment by ejconlon** [comment]
MERGED! GREAT JOB @luc-tielen !

**Comment by luc-tielen** [comment]
Hey, thanks for merging it in!
.. But please be aware that it is not finished yet.

Things still left to be done:
```
- CI integration
- Docs generation mostly works but it still gives some bugs. I already have a failing test that can reproduce the failing case.
- Some commands still need to be implemented: test, repl, ... (look at source code to see which commands still need to be done)
- Parallellization of compiling: this should be easy, I already did some steps towards this but for now it is all done sequentially (compiler should be able to handle this).
```

Compilation and setup of project should work (which is what the tool mostly does).

I actually think most of the work is behind us now, we have a decent setup for implementing the remaining commands.
This week and next week I have some more time, maybe I can find some time to finish the remaining stuff.

**Comment by ejconlon** [comment]
Yes, of course.  I wanted to merge into mainline so we can start doing more granular pull-requests for individual features.  In the next few days I want to make sure the integration test works and I want to make CI work.
