### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by ejconlon** [ejconlon/idream#2]
The biggest obstacle is having a compiled idris for whatever linux we're running on.  Travis just bails because it takes so long, so I have turned it off.

**Comment by ejconlon** [comment]
Need to revisit ejconlon/idr-distribution to get resonable images.

**Comment by luc-tielen** [comment]
I think we can win a lot here by using a docker image that has most things preinstalled so that it would only have to build idream itself..
Container would contain mostly `idris`, `ruby + rspec` (for testing) and `ghc + stack` (for building idream)?

**Comment by ejconlon** [comment]
I want to revisit my idris deb packaging (https://github.com/ejconlon/idr-distribution) so we can get a base image with idris itself.  Then I want to do the same for idream so we have an idris/idream image.

**Comment by luc-tielen** [comment]
I took a quick look at it, but couldn't figure out what it's for?
Is it for building a docker image?
I do this quite a bit (also for work), so I can help if you want to.
I'm still busy for a few days but then I got a week off for tinkering with some stuff :)

**Comment by ejconlon** [comment]
Frankly speaking, it's a mess now.  The main goal is to make _binary_ deb releases for Idris.  I would like to expand it to make tgz releases or any other package manager formats.  (Though I will say I haven't done due diligence to relocatability...).  There is a nest of scripts there to support building with pluggable base images and scripts and a script to upload releases to github.  We can use the binary releases there to build images for CI here.  Building binary packages for idream would be the next step once all that is running smoothly.
