### ISSUE TITLE
Redesign of package building

### ISSUE THREAD

**Issue by luc-tielen** [ejconlon/idream#4]
The building of packages and dependencies should be done based a (dependency) tree.
The tree would be constructed by parsing the .json files located in the various packages (and using some sort of monoid to combine all results together in an easy way).
Each dependency used needs to be added in the json file of that package but also in the root package that is being built (explicitness / clarity).

Once the tree is constructed, it is easy to see which packages need to be built first (leaf nodes), and then work upwards to the top level of the tree.

For the actual building of the packages, I think if we use an applicative style approach combined with a dependency tree we can probably parallellize the compiling of packages.

**Comment by ejconlon** [comment]
Sounds good to me, but we would have to confirm that Idris itself is ok being invoked in parallel :)
